# Generated by Django 2.1 on 2020-08-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_id',
            field=models.IntegerField(max_length=3),
        ),
    ]
