# Generated by Django 2.1 on 2020-08-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200805_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teachers',
            new_name='teacher',
        ),
    ]
