# Generated by Django 2.1 on 2020-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.IntegerField(max_length=12),
        ),
    ]
